seed_everything: true
name: 'base_checkpoint'
ckpt_path: null
output: './output'
group: 'checkpoint'
logger: 'wandb'
project: 'base'
model:
  class_path: src.models.GS3d
  init_args:
    sh_degree: 3
    percent_dense: 0.01
    warm_up: 3000
    position_lr_init: 0.00016
    position_lr_final: 0.0000016
    position_lr_delay_mult: 0.01
    position_lr_max_steps: 30000
    deform_lr_max_steps: 40000
    feature_lr: 0.0025
    opacity_lr: 0.05
    scaling_lr: 0.001 # for Effgs, to scaling_lr=0.005?
    rotation_lr: 0.001
    lambda_dssim: 0.2
    densification_interval: 100
    opacity_reset_interval: 3000
    densify_from_iter: 500
    densify_until_iter: 15000
    densify_grad_threshold: 0.0002
    use_static: false
    init_mode: "EffGS"
    motion_mode: "EffGS"
data:
  class_path: src.data.NerfiesDataModule
  init_args:
    datadir: '/users/yliang51/data/yliang51/Gaussian4D_depre/data/hypernerf/vrig-chicken'
    eval: True
    ratio: 0.25
    white_background: true
    batch_size: 1
trainer:
  logger: true
  enable_checkpointing: true
  num_nodes: 1
  devices: "auto"
  enable_progress_bar: true
  max_epochs: 1
  max_steps: 40000
  val_check_interval: 1000
  log_every_n_steps: 50
  accelerator: "gpu"
  strategy: "ddp_find_unused_parameters_true"
  precision: 32 # cannot set to 16; otherwise ssim bug and https://stackoverflow.com/questions/75969294/assertionerror-no-inf-checks-were-recorded-for-this-optimizer
  enable_model_summary: true
  callbacks:
    - class_path: "lightning.pytorch.callbacks.ModelCheckpoint"
      init_args:
        monitor: 'val/avg_ssim_train'
        dirpath: null
        filename: 'model-{step:06d}-{val/avg_ssim_train:.2f}'
        save_top_k: 3
        mode: 'max'
        save_last: true
        save_on_train_epoch_end: true
  

